Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - "bin/bundle"

Metrics/MethodLength:
  Exclude:
    - "bin/bundle"
    - "db/migrate/20220623085059_create_active_storage_tables.active_storage.rb"
    - "db/migrate/20220727135628_create_activities.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "bin/bundle"

Layout/LineLength:
  Exclude:
    - "bin/bundle"
    - "config/initializers/devise.rb"
    - "db/seeds.rb"
    - "config/initializers/simple_form_bootstrap.rb"
    - "config/initializers/simple_form.rb"

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
    - "config/initializers/simple_form_bootstrap.rb"
    - "config/environments/development.rb"
    - "app/admin/authors.rb"
    - "app/admin/books.rb"
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/20220623085059_create_active_storage_tables.active_storage.rb"

Lint/MissingSuper:
  Exclude:
    - 'app/operations/**/*'
    - 'app/services/**/*'