version: 2.1

jobs:
  build:
    working_directory: ~/CircleCI
    docker:
      - image: cimg/ruby:3.1.2
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: library
          POSTGRES_PASSWORD: library-password
    steps:
      - checkout
      - run:
          name: Ruby version
          command: ruby --version
      - run:
          name: Install bundler and gems
          command: |
            gem install bundler
            bundle install
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: bundle exec rails db:setup
  test:
    working_directory: ~/CircleCI
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  test-task:
    jobs:
      - build
      - test:
          requires:
            - build
