version: 2.1

jobs:
  build:
    working_directory: ~/Circle
    docker:
      - image: cimg/ruby:3.1.2
      - image: cimg/postgres:12.11
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: library
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Ruby version
          command: ruby --version
      - run:
          name: Install bundler and gems
          command: |
            gem install bundler
            bundle install
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: bundle exec rails db:setup
      - run: brew services start opensearch
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  test-task:
    jobs:
      - build
