version: 2.1

jobs:
  build:
    working_directory: ~/Circle
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: library
          POSTGRES_PASSWORD: postgres
#      - image: opensearchproject/opensearch:latest
#        environment:
#          - transport.host: localhost
#          - http.port: 9200
#          - discovery.type: single-node
#          - plugins.security.disabled: true
    steps:
      - checkout
      - run:
          name: Ruby version
          command: ruby --version

      - run:
          name: Bundler version
          command: bundler --version

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install
      - run: bundle clean --force
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Rubocop
          command: rubocop

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: bundle exec rails db:setup

      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  test-task:
    jobs:
      - build
